Minimum working connection settings
i8enn/pydantic-odm pull request #11
Opened 2019-12-23 11:56 UTC by hongquan

On Linux, especially in development, authentication for local MongoDB is not needed to set. It help save effort of keeping secret info around. This PR allows to connect to a local MongoDB server with minimum settings.

2019-12-28 06:38 UTC, i8enn commented
Hi, @hongquan! Thank you very much for your contribution to the project! Sorry for the long answer time: lately I have been overwhelmed with work, but I hope everything will return to normal after the new year.

Regarding the pull request - this is a good idea - i missed this problem (especially with the introduction of the `authMechanism` parameter). 

I added of changing to your pull request, and also commented on the changed place - please check, and if everything is fine - tell me and I will apply these changes.

2019-12-28 06:53 UTC, i8enn requested changes

2019-12-28 06:53 UTC, i8enn commented on pydantic_odm/db.py
> +            connection_params = {
It seems to me that this configuration option will be simpler and more understandable. 
If something goes wrong - the driver (motor, pymongo) itself will tell us about it directly. 
In our case, this give is a minimum of logic for connecting to the MongoDB.

2019-12-30 02:27 UTC, hongquan commented
@i8enn I agree with your addition.

2019-12-30 05:33 UTC, i8enn approved these changes

2019-12-30 05:34 UTC, merged